* motiviation
Digital computer is not a robust system. If a strong solar wind randomly flip over the bits in all computers on the earth, it will be hurt. 

* goal
- print all existing slip-box notes into physical papers

  The connection should be left as it is. The print out version should have the same protocal to connect new with old notes.

* steps
** write checker to check all the formats
This will be a huge process. It's better to define the template as versetial as possible
*** https://github.com/randomwangran/ox-md-with-transclusion.el
This is an embark to work with.
** md5 all files when decide to print slip-notes
Next time, when 2nd print, there's no need to print files that are not changed 

* todo
** check the length of the notes
Should forces a limitation of a note to construct a physical note. 
Check the discussion here: https://forum.zettelkasten.de/discussion/1651/how-long-a-zettel-is-too-long#latest
** resolve the relation within an Org-mode file
Headline1 is the father of headline2. This might not be resolved by database.
** 2-way-transform
Restore from a physical system into digitial one is not easy but possible.

The layout should be design such that the scanner software is able to pickup the meta-info with easy. 

This will be a promosing idea to work with. Since the user can work both from the physical ZK and digitial computers.
